/**
 * Birth-time rectification service.
 *
 * Every call returns the complete wizard state, so the screen never tracks
 * where the user is on its own — it renders whatever step the server reports.
 * That is what makes the journey resumable after the app is killed at any
 * point, and it means an interrupted request can simply be retried.
 */

import { authApi } from './sessionManager';
import { cacheInvalidatePrefix } from './cache';

export type RectificationStep =
    | 'source_officielle'
    | 'fenetre'
    | 'collecte'
    | 'calcul'
    | 'resultat'
    | 'boucle_active'
    | 'adoption'
    | 'termine';

export type SourceChoice = 'has_time' | 'requested' | 'impossible';

/** Derived from what the user filled in — never asked for directly. */
export type DatePrecision = 'day' | 'week' | 'month' | 'year';

export type Intensity = 'moment' | 'turning_point' | 'life_changing';

export interface RectificationEvent {
    date: string;
    precision: DatePrecision;
    intensity: Intensity;
    sudden: boolean;
    valence?: string | null;
    category?: string | null;
    title?: string | null;
}

export interface EventInput {
    year: number;
    month?: number | null;
    day?: number | null;
    intensity?: Intensity;
    sudden?: boolean;
    valence?: 'difficile' | 'heureux' | 'neutre' | null;
    category?: string;
    title?: string | null;
}

export interface WindowAnswers {
    day_night?: 'jour' | 'nuit' | 'aucune_idee';
    memory?: string;
    memory_note?: string;
    date_certain?: boolean;
}

/** A point of the posterior curve, as drawn on the dial. */
export interface CurvePoint {
    t: string;
    p: number;
}

export interface RectificationResult {
    status: 'conclusive' | 'multimodal' | 'inconclusive';
    coherence: number;
    contrast: number;
    entropy: number;
    curve: CurvePoint[];
    what_would_help: string[];
    premium: boolean;
    calculated_at: string;
    /** Premium only — a time is never returned without its uncertainty. */
    estimate?: {
        time: string;
        uncertainty_minutes: number;
        coherence: number;
        from: string;
        to: string;
    };
    candidate_times?: { time: string; probability: number }[];
    contributions?: { event: string; text: string; orb: number }[];
    hold_out?: { event: number; mode_stable: boolean; event_predicted: boolean; passed: boolean }[];
    /** Free tier only — the shape of the answer, with no clock time in it. */
    teaser?: { signs: string[]; label: string };
}

/** A question generated by the active loop (spec §8). */
export interface LoopQuestion {
    key: string;
    question: string;
    from: string;
    to: string;
    midpoint: string;
    /** Expected entropy reduction in bits — diagnostic, never shown to the user. */
    expected_gain: number;
}

export type LoopAnswer = 'rien' | 'difficile' | 'heureux' | 'tournant' | 'sais_pas';

export interface DialState {
    uncertainty_minutes: number | null;
    events: number;
    day_dated: number;
    /** Exact shortfall, e.g. "Il te manque 1 événement pour lancer le calcul". */
    missing: string[];
    ready: boolean;
}

export interface RectificationState {
    success: boolean;
    session: {
        step: RectificationStep;
        source_choice: SourceChoice | null;
        known_time: string | null;
        window_answers: WindowAnswers;
        window: { start: number; end: number } | null;
        events: RectificationEvent[];
        asked_questions: string[];
        pending_question: LoopQuestion | null;
        result: RectificationResult | null;
        calculated_at: string | null;
        updated_at: string;
    };
    /** Present on the active-loop endpoints; null when the loop should stop. */
    question?: LoopQuestion | null;
    dial: DialState;
    limits: {
        premium: boolean;
        free_max_events: number;
        min_events: number;
        min_day_dated: number;
    };
}

const BASE = '/api/rectification/session';

/**
 * The inference runs a posterior over up to 720 candidate charts, so the
 * mutating calls are seconds rather than milliseconds. Generous timeouts here
 * are deliberate: a dropped calculation would lose the user's place.
 */
const CALC_TIMEOUT_MS = 45_000;
const MUTATION_TIMEOUT_MS = 30_000;

export async function getRectificationState(): Promise<RectificationState> {
    return authApi.get<RectificationState>(BASE);
}

export async function submitOfficialSource(
    choice: SourceChoice,
    time?: string,
): Promise<RectificationState> {
    const state = await authApi.post<RectificationState>(
        `${BASE}/official-source`,
        { choice, time },
        { timeoutMs: MUTATION_TIMEOUT_MS },
    );

    // A known birth time changes the natal chart everywhere in the app.
    if (choice === 'has_time') invalidateChartCaches();

    return state;
}

export async function submitWindow(answers: WindowAnswers): Promise<RectificationState> {
    return authApi.post<RectificationState>(`${BASE}/window`, answers as Record<string, unknown>, {
        timeoutMs: MUTATION_TIMEOUT_MS,
    });
}

export async function addRectificationEvent(input: EventInput): Promise<RectificationState> {
    return authApi.post<RectificationState>(`${BASE}/events`, input as unknown as Record<string, unknown>, {
        timeoutMs: MUTATION_TIMEOUT_MS,
    });
}

export async function removeRectificationEvent(index: number): Promise<RectificationState> {
    return authApi.delete<RectificationState>(`${BASE}/events/${index}`, {
        timeoutMs: MUTATION_TIMEOUT_MS,
    });
}

export async function runRectification(): Promise<RectificationState> {
    return authApi.post<RectificationState>(`${BASE}/calculate`, undefined, {
        timeoutMs: CALC_TIMEOUT_MS,
    });
}

/**
 * Ask the server for the next discriminating question of the active loop.
 * A null `question` in the response means the loop is done.
 */
export async function getNextQuestion(): Promise<RectificationState> {
    return authApi.get<RectificationState>(`${BASE}/question`, { timeoutMs: CALC_TIMEOUT_MS });
}

export async function answerQuestion(answer: LoopAnswer): Promise<RectificationState> {
    return authApi.post<RectificationState>(`${BASE}/question`, { answer }, { timeoutMs: CALC_TIMEOUT_MS });
}

export async function adoptRectifiedTime(): Promise<RectificationState> {
    const state = await authApi.post<RectificationState>(`${BASE}/adopt`, undefined, {
        timeoutMs: MUTATION_TIMEOUT_MS,
    });

    // Houses and Ascendant become available — everything derived is now stale.
    invalidateChartCaches();

    return state;
}

export async function revertToDeclaredTime(time: string | null): Promise<void> {
    await authApi.post(`${BASE}/revert`, { time }, { timeoutMs: MUTATION_TIMEOUT_MS });
    invalidateChartCaches();
}

function invalidateChartCaches(): void {
    // Fire-and-forget: cacheInvalidatePrefix swallows its own errors, and the
    // caller should not wait on disk cleanup before rendering the new state.
    void cacheInvalidatePrefix('natal');
    void cacheInvalidatePrefix('horoscope');
    void cacheInvalidatePrefix('transits');
}

/**
 * Event categories offered on the collection screen (spec §5.1).
 *
 * `sudden` pre-fills the character toggle and is what earns the "précision ++"
 * badge: unplanned events are datable to the day and carry the most signal.
 * The badge orients the user without ever explaining the astrology behind it.
 */
export const EVENT_CATEGORIES: {
    key: string;
    label: string;
    sudden: boolean;
    /** Contextual nudge shown when the user skips the day (spec §5.2). */
    dayHint: string;
}[] = [
    { key: 'travail', label: 'Changement de travail', sudden: true, dayHint: 'La date est sur ton contrat ou ton relevé de carrière.' },
    { key: 'rupture', label: 'Rupture / divorce', sudden: true, dayHint: 'Regarde tes photos ou tes messages de l’époque.' },
    { key: 'deces', label: 'Décès d’un proche', sudden: true, dayHint: 'La date est sur l’avis d’obsèques.' },
    { key: 'accident', label: 'Accident / opération', sudden: true, dayHint: 'Ton compte rendu d’hospitalisation la porte.' },
    { key: 'rencontre', label: 'Rencontre marquante', sudden: true, dayHint: 'Ta première conversation est peut-être encore dans ton téléphone.' },
    { key: 'mariage', label: 'Mariage / pacs', sudden: false, dayHint: 'Sur le faire-part ou l’acte.' },
    { key: 'naissance', label: 'Naissance d’un enfant', sudden: false, dayHint: 'Sur le livret de famille.' },
    { key: 'demenagement', label: 'Déménagement / expatriation', sudden: false, dayHint: 'Sur ton bail ou ton état des lieux.' },
    { key: 'immobilier', label: 'Achat immobilier', sudden: false, dayHint: 'Sur l’acte notarié.' },
    { key: 'charniere', label: 'Période charnière', sudden: false, dayHint: 'Même approximative, la date aide.' },
    { key: 'autre', label: 'Autre tournant', sudden: false, dayHint: 'Même approximative, la date aide.' },
];

export const INTENSITY_LABELS: { key: Intensity; label: string }[] = [
    { key: 'moment', label: 'Un moment' },
    { key: 'turning_point', label: 'Un tournant' },
    { key: 'life_changing', label: 'Ça a tout changé' },
];

/**
 * The window chips of spec §4, one screen at a time.
 */
export const MEMORY_CHIPS: { key: string; label: string }[] = [
    { key: 'matin_tot', label: 'Le matin tôt' },
    { key: 'matinee', label: 'La matinée' },
    { key: 'apres_midi', label: 'L’après-midi' },
    { key: 'soiree', label: 'La soirée' },
    { key: 'nuit', label: 'La nuit' },
    { key: 'autour_minuit', label: 'Autour de minuit' },
    { key: 'aucune_idee', label: 'Aucune idée' },
];

/**
 * Format an uncertainty the way the spec insists it always appears: never a
 * bare time, always the margin next to it.
 */
export function formatUncertainty(minutes: number | null | undefined): string {
    if (minutes === null || minutes === undefined) return '—';
    if (minutes < 60) return `±${minutes} min`;

    const hours = Math.floor(minutes / 60);
    const rest = minutes % 60;

    return rest === 0 ? `±${hours} h` : `±${hours} h ${String(rest).padStart(2, '0')}`;
}
