/**
 * Help Center — comprehensive guide to the app and astrological concepts.
 * Accessible from the profile screen.
 */

import React, { useState } from 'react';
import {
    View,
    Text,
    ScrollView,
    Pressable,
    StyleSheet,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useRouter } from 'expo-router';
import { Feather } from '@expo/vector-icons';
import { useTranslation } from 'react-i18next';
import { colors, spacing, radius, fonts } from '@/theme';
import { TabHeader } from '@/components/ui';

// ─── Content ──────────────────────────────────────────────────────────────────

const PAGES_CONTENT = (fr: boolean) => [
    {
        icon: '✦' as const,
        name: fr ? 'Thème natal' : 'Natal Chart',
        description: fr
            ? "Votre carte du ciel au moment exact de votre naissance. Les positions planétaires révèlent votre personnalité, vos forces naturelles et vos défis de vie. Appuyez sur une planète pour voir son interprétation détaillée."
            : "Your sky map at the exact moment of your birth. Planetary positions reveal your personality, natural strengths, and life challenges. Tap a planet for a detailed interpretation.",
    },
    {
        icon: '♡' as const,
        name: fr ? 'Compatibilité' : 'Compatibility',
        description: fr
            ? "Analyse synastrique entre votre thème et celui d'un partenaire. Entrez ses données de naissance pour obtenir un score sur 5 dimensions et une analyse complète de vos dynamiques de couple."
            : "Synastric analysis between your chart and a partner's. Enter their birth data to get a score across 5 dimensions and a full analysis of your couple dynamics.",
    },
    {
        icon: '⚡' as const,
        name: fr ? 'Transits' : 'Transits',
        description: fr
            ? "Les planètes en mouvement aujourd'hui en relation avec votre thème natal. L'onglet Frise donne les grandes tendances à venir ; l'onglet Calendrier vous permet de consulter les aspects jour par jour."
            : "Planets in motion today in relation to your natal chart. The Timeline tab shows upcoming trends; the Calendar tab lets you browse aspects day by day.",
    },
    {
        icon: '⏱' as const,
        name: fr ? 'Miroir temporel' : 'Time Mirror',
        description: fr
            ? "Consultez les transits planétaires à n'importe quel âge de votre vie — passé ou futur. Idéal pour comprendre une période marquante ou anticiper une transition importante."
            : "View planetary transits at any age in your life — past or future. Ideal for understanding a significant period or anticipating an important transition.",
    },
    {
        icon: '✦' as const,
        name: fr ? 'Chat astro' : 'Astro Chat',
        description: fr
            ? "Votre assistant IA spécialisé en astrologie. Posez toutes vos questions sur votre thème natal, un transit, un aspect, ou n'importe quel sujet astrologique. L'IA connaît votre thème et y fait référence."
            : "Your AI assistant specialized in astrology. Ask any question about your natal chart, a transit, an aspect, or any astrological topic. The AI knows your chart and references it.",
    },
    {
        icon: '☀' as const,
        name: fr ? 'Horoscope du jour' : 'Daily Horoscope',
        description: fr
            ? "Prévisions quotidiennes générées par l'IA à partir de votre thème natal et des transits du jour. Se divise en quatre sections : Aperçu général, Amour, Énergie et Conseil du jour."
            : "Daily forecasts generated by AI from your natal chart and today's transits. Divided into four sections: General Overview, Love, Energy, and Daily Advice.",
    },
];

const PLANETS_CONTENT = (fr: boolean) => [
    { symbol: '☉', color: '#e9c349', name: fr ? 'Soleil' : 'Sun', description: fr ? "Identité profonde, vitalité, ego, volonté. Représente qui vous êtes en essence et ce qui vous donne de l'énergie." : "Core identity, vitality, ego, will. Represents who you truly are and what gives you energy." },
    { symbol: '☽', color: '#c8bfff', name: fr ? 'Lune' : 'Moon', description: fr ? "Émotions, instincts, mémoire, besoins intérieurs. Gouverne votre monde émotionnel et vos réactions instinctives." : "Emotions, instincts, memory, inner needs. Governs your emotional world and instinctive reactions." },
    { symbol: '☿', color: '#60a5fa', name: fr ? 'Mercure' : 'Mercury', description: fr ? "Pensée, communication, logique, déplacements. Influence la façon dont vous apprenez, parlez et traitez l'information." : "Thought, communication, logic, travel. Influences how you learn, speak, and process information." },
    { symbol: '♀', color: '#f472b6', name: fr ? 'Vénus' : 'Venus', description: fr ? "Amour, beauté, valeurs, plaisir, argent. Gouverne vos attractions, ce qui vous plaît et votre rapport à l'abondance." : "Love, beauty, values, pleasure, money. Governs your attractions and your relationship to abundance." },
    { symbol: '♂', color: '#fb923c', name: fr ? 'Mars' : 'Mars', description: fr ? "Énergie, désir, action, courage, conflit. La planète qui vous pousse à agir, à conquérir et à défendre ce qui compte." : "Energy, desire, action, courage, conflict. The planet that drives you to act, conquer, and defend what matters." },
    { symbol: '♃', color: '#4ade80', name: fr ? 'Jupiter' : 'Jupiter', description: fr ? "Expansion, chance, sagesse, foi, excès. Apporte croissance et opportunités là où il transite — parfois jusqu'à l'exagération." : "Expansion, luck, wisdom, faith, excess. Brings growth and opportunity where it transits — sometimes to excess." },
    { symbol: '♄', color: '#a78bfa', name: fr ? 'Saturne' : 'Saturn', description: fr ? "Discipline, limites, karma, durée, responsabilité. Enseigne par les contraintes et récompense l'effort patient sur le long terme." : "Discipline, limits, karma, time, responsibility. Teaches through constraints and rewards patient effort over time." },
    { symbol: '♅', color: '#38bdf8', name: fr ? 'Uranus' : 'Uranus', description: fr ? "Révolution, liberté, innovation, ruptures soudaines. Brise les structures établies pour libérer un potentiel plus authentique." : "Revolution, freedom, innovation, sudden breaks. Shatters established structures to free a more authentic potential." },
    { symbol: '♆', color: '#818cf8', name: fr ? 'Neptune' : 'Neptune', description: fr ? "Spiritualité, intuition, illusion, dissolution. Dissout les frontières du moi et ouvre à la transcendance — ou à la confusion." : "Spirituality, intuition, illusion, dissolution. Dissolves ego boundaries, opening to transcendence — or confusion." },
    { symbol: '♇', color: '#f87171', name: fr ? 'Pluton' : 'Pluto', description: fr ? "Transformation radicale, pouvoir, mort et renaissance, profondeur. Planète des grandes mutations qui détruit pour mieux reconstruire." : "Radical transformation, power, death and rebirth, depth. Planet of great mutations that destroys to better rebuild." },
    { symbol: 'ASC', color: colors.onSurfaceMuted, name: 'Ascendant', description: fr ? "Le signe qui se levait à l'Est au moment de votre naissance. Votre masque social, première impression, façon d'aborder le monde." : "The sign rising in the East at the moment of your birth. Your social mask, first impression, and way of approaching the world." },
];

const ASPECTS_CONTENT = (fr: boolean) => [
    { symbol: '☌', color: '#e9c349', name: fr ? 'Conjonction' : 'Conjunction', badge: '0°', description: fr ? "Fusion totale de deux énergies. Amplifie et intensifie les deux principes — pour le meilleur ou pour le pire. Moment clé pour agir." : "Total fusion of two energies. Amplifies and intensifies both principles — for better or worse. A key moment to act." },
    { symbol: '☍', color: '#cf6679', name: fr ? 'Opposition' : 'Opposition', badge: '180°', description: fr ? "Tension entre deux pôles opposés. Invite à trouver l'équilibre entre des besoins contradictoires, souvent via les relations." : "Tension between two opposite poles. Invites balance between conflicting needs, often through relationships." },
    { symbol: '△', color: '#4ade80', name: fr ? 'Trigone' : 'Trine', badge: '120°', description: fr ? "Harmonie naturelle et facilité de flux. Les choses avancent sans effort. Excellent pour créer et saisir les opportunités." : "Natural harmony and easy flow. Things progress effortlessly. Excellent for creating and seizing opportunities." },
    { symbol: '□', color: '#fb923c', name: fr ? 'Carré' : 'Square', badge: '90°', description: fr ? "Friction et défi qui pousse à l'action. Moteur de croissance : inconfortable, mais puissant pour briser les blocages." : "Friction that pushes you to act. A growth engine: uncomfortable but powerful for breaking through blocks." },
    { symbol: '⚹', color: '#60a5fa', name: 'Sextile', badge: '60°', description: fr ? "Opportunité douce et coopération. Énergie favorable qui demande un léger effort. Propice aux échanges et nouvelles connexions." : "Soft opportunity and cooperation. A favorable energy that needs a small push. Good for exchanges and new connections." },
];

const HOUSES_CONTENT = (fr: boolean) => [
    { number: '1', name: fr ? 'Personnalité' : 'Self', description: fr ? "L'Ascendant. Apparence, identité, façon d'aborder le monde, corps physique." : "The Ascendant. Appearance, identity, how you approach the world, physical body." },
    { number: '2', name: fr ? 'Ressources' : 'Resources', description: fr ? "Finances personnelles, valeurs profondes, possessions matérielles, sens de la sécurité." : "Personal finances, deep values, material possessions, sense of security." },
    { number: '3', name: fr ? 'Communication' : 'Communication', description: fr ? "Pensée, langage, fratrie, déplacements courts, apprentissage, environnement proche." : "Thought, language, siblings, short trips, learning, immediate environment." },
    { number: '4', name: fr ? 'Foyer' : 'Home', description: fr ? "Famille, racines, foyer, fondations émotionnelles, parent nourricier, fin de vie." : "Family, roots, home, emotional foundations, nurturing parent, end of life." },
    { number: '5', name: fr ? 'Créativité' : 'Creativity', description: fr ? "Créativité, enfants, amours, plaisirs, jeux, expression personnelle, spéculation." : "Creativity, children, romance, pleasures, play, self-expression, speculation." },
    { number: '6', name: fr ? 'Santé & Service' : 'Health & Service', description: fr ? "Travail quotidien, santé, hygiène de vie, service aux autres, animaux de compagnie." : "Daily work, health, lifestyle habits, service to others, pets." },
    { number: '7', name: fr ? 'Partenariats' : 'Partnerships', description: fr ? "Mariage, associations, relations intimes, contrats, adversaires, projections sur l'autre." : "Marriage, partnerships, intimate relations, contracts, open enemies, projections." },
    { number: '8', name: fr ? 'Transformation' : 'Transformation', description: fr ? "Sexualité, héritages, mort et renaissance, ressources partagées, profondeurs psychologiques." : "Sexuality, inheritance, death and rebirth, shared resources, psychological depths." },
    { number: '9', name: fr ? 'Philosophie' : 'Philosophy', description: fr ? "Voyages lointains, philosophie, spiritualité, études supérieures, religion, étranger." : "Long-distance travel, philosophy, spirituality, higher education, religion, foreign lands." },
    { number: '10', name: fr ? 'Carrière' : 'Career', description: fr ? "Carrière, réputation, ambition sociale, vie publique, parent autoritaire, MC (Milieu du Ciel)." : "Career, reputation, social ambition, public life, authority parent, MC (Midheaven)." },
    { number: '11', name: fr ? 'Idéaux' : 'Ideals', description: fr ? "Amis, groupes, associations, idéaux, espoirs, conscience collective, humanitaire." : "Friends, groups, associations, ideals, hopes, collective consciousness, humanitarian causes." },
    { number: '12', name: fr ? 'Inconscient' : 'Unconscious', description: fr ? "Inconscient, isolement, karma, spiritualité profonde, ennemis cachés, lieux de retraite." : "Unconscious, isolation, karma, deep spirituality, hidden enemies, places of retreat." },
];

const GLOSSARY_CONTENT = (fr: boolean) => [
    { name: fr ? 'Transit' : 'Transit', description: fr ? "Le mouvement actuel d'une planète en relation avec une planète de votre thème natal. Les transits indiquent les thèmes et les énergies actives dans votre vie." : "The current movement of a planet in relation to a planet in your natal chart. Transits indicate the themes and energies active in your life." },
    { name: fr ? 'Aspect' : 'Aspect', description: fr ? "Angle géométrique entre deux planètes (conjonction 0°, opposition 180°, trigone 120°, carré 90°, sextile 60°). Les aspects créent des synergies ou des tensions." : "Geometric angle between two planets (conjunction 0°, opposition 180°, trine 120°, square 90°, sextile 60°). Aspects create synergies or tensions." },
    { name: fr ? 'Orbe' : 'Orb', description: fr ? "Marge de tolérance en degrés autour d'un aspect exact. Un orbe serré (< 3°) produit un aspect plus intense. Les orbes larges (> 8°) sont plus diffus." : "Degree of tolerance around an exact aspect. A tight orb (< 3°) produces a more intense aspect. Wide orbs (> 8°) are more diffuse." },
    { name: fr ? 'Rétrograde' : 'Retrograde', description: fr ? "Quand une planète semble reculer dans le ciel (phénomène optique). Période d'intériorisation, de révision et de reconsidération des thèmes liés à cette planète." : "When a planet appears to move backward in the sky (optical phenomenon). A period of introspection, revision, and reconsideration of themes related to that planet." },
    { name: fr ? 'Synastrie' : 'Synastry', description: fr ? "Technique astrologique comparant deux thèmes natals en superposant les planètes de l'un sur les maisons de l'autre pour analyser la compatibilité." : "Astrological technique comparing two natal charts by overlaying the planets of one on the houses of the other to analyze compatibility." },
    { name: fr ? 'Ascendant (ASC)' : 'Ascendant (ASC)', description: fr ? "Le signe du zodiaque qui se levait à l'est de l'horizon au moment exact de votre naissance. Il représente votre personnalité apparente et première impression." : "The zodiac sign rising on the eastern horizon at the exact moment of your birth. It represents your outer personality and first impression." },
    { name: fr ? 'MC — Milieu du Ciel' : 'MC — Midheaven', description: fr ? "Le point culminant de l'écliptique au moment de votre naissance. Associé à la carrière, la réputation et les ambitions sociales (maison 10)." : "The highest point of the ecliptic at the moment of your birth. Associated with career, reputation, and social ambitions (house 10)." },
    { name: fr ? 'Nœud Nord (☊)' : 'North Node (☊)', description: fr ? "Point karmique lunaire symbolisant votre direction d'évolution dans cette vie. Ce que vous êtes invité à développer et expérimenter." : "Lunar karmic point symbolizing your evolutionary direction in this life. What you are invited to develop and experience." },
    { name: fr ? 'Nœud Sud (☋)' : 'South Node (☋)', description: fr ? "Opposé au Nœud Nord. Représente vos acquis passés, vos dons naturels et votre zone de confort karmique à transcender." : "Opposite the North Node. Represents your past skills, natural gifts, and karmic comfort zone to transcend." },
    { name: fr ? 'Stellium' : 'Stellium', description: fr ? "Concentration de 3 planètes ou plus dans un même signe ou une même maison. Crée une forte concentration d'énergie dans ce domaine." : "Concentration of 3 or more planets in the same sign or house. Creates a strong concentration of energy in that area." },
];

// ─── Section types ────────────────────────────────────────────────────────────

type SectionId = 'pages' | 'planets' | 'aspects' | 'houses' | 'glossary';

// ─── Accordion Section ────────────────────────────────────────────────────────

function AccordionSection({
    id,
    title,
    isOpen,
    onToggle,
    children,
}: {
    id: SectionId;
    title: string;
    isOpen: boolean;
    onToggle: () => void;
    children: React.ReactNode;
}) {
    return (
        <View style={acc.wrapper}>
            <Pressable style={acc.header} onPress={onToggle} android_ripple={{ color: 'rgba(255,255,255,0.05)' }}>
                <Text style={acc.headerText}>{title}</Text>
                <Feather
                    name={isOpen ? 'chevron-up' : 'chevron-down'}
                    size={16}
                    color={colors.onSurfaceMuted}
                />
            </Pressable>
            {isOpen && <View style={acc.body}>{children}</View>}
        </View>
    );
}

// ─── Main Screen ──────────────────────────────────────────────────────────────

export default function HelpScreen() {
    const router = useRouter();
    const { i18n: i18nHook } = useTranslation();
    const fr = i18nHook.language === 'fr';
    const [openSection, setOpenSection] = useState<SectionId | null>('pages');

    const toggle = (id: SectionId) => setOpenSection(prev => prev === id ? null : id);

    const pages   = PAGES_CONTENT(fr);
    const planets = PLANETS_CONTENT(fr);
    const aspects = ASPECTS_CONTENT(fr);
    const houses  = HOUSES_CONTENT(fr);
    const glossary = GLOSSARY_CONTENT(fr);

    return (
        <View style={styles.root}>
            <SafeAreaView style={styles.safe} edges={['top']}>
                <TabHeader onBack={() => router.back()} />

                <ScrollView
                    showsVerticalScrollIndicator={false}
                    contentContainerStyle={styles.scrollContent}
                >
                    <Text style={styles.pageTitle}>{fr ? 'Centre d\'aide' : 'Help Center'}</Text>
                    <Text style={styles.intro}>
                        {fr
                            ? "Tout ce que vous devez savoir sur Lunestia et l'astrologie."
                            : "Everything you need to know about Lunestia and astrology."}
                    </Text>

                    {/* Pages */}
                    <AccordionSection
                        id="pages"
                        title={fr ? 'Les pages de l\'app' : 'App pages'}
                        isOpen={openSection === 'pages'}
                        onToggle={() => toggle('pages')}
                    >
                        {pages.map((p, i) => (
                            <View key={i} style={styles.item}>
                                <View style={styles.iconBubble}>
                                    <Text style={styles.iconText}>{p.icon}</Text>
                                </View>
                                <View style={styles.itemBody}>
                                    <Text style={styles.itemName}>{p.name}</Text>
                                    <Text style={styles.itemDesc}>{p.description}</Text>
                                </View>
                            </View>
                        ))}
                    </AccordionSection>

                    {/* Planets */}
                    <AccordionSection
                        id="planets"
                        title={fr ? 'Les planètes' : 'Planets'}
                        isOpen={openSection === 'planets'}
                        onToggle={() => toggle('planets')}
                    >
                        {planets.map((p, i) => (
                            <View key={i} style={styles.item}>
                                <View style={[styles.symbolBubble, { backgroundColor: `${p.color}20` }]}>
                                    <Text style={[
                                        styles.symbol,
                                        { color: p.color },
                                        p.symbol.length > 1 && styles.symbolSmall,
                                    ]}>
                                        {p.symbol}
                                    </Text>
                                </View>
                                <View style={styles.itemBody}>
                                    <Text style={[styles.itemName, { color: p.color }]}>{p.name}</Text>
                                    <Text style={styles.itemDesc}>{p.description}</Text>
                                </View>
                            </View>
                        ))}
                    </AccordionSection>

                    {/* Aspects */}
                    <AccordionSection
                        id="aspects"
                        title={fr ? 'Les aspects' : 'Aspects'}
                        isOpen={openSection === 'aspects'}
                        onToggle={() => toggle('aspects')}
                    >
                        {aspects.map((a, i) => (
                            <View key={i} style={styles.item}>
                                <View style={[styles.symbolBubble, { backgroundColor: `${a.color}20` }]}>
                                    <Text style={[styles.symbol, { color: a.color }]}>{a.symbol}</Text>
                                </View>
                                <View style={styles.itemBody}>
                                    <View style={styles.itemRow}>
                                        <Text style={[styles.itemName, { color: a.color }]}>{a.name}</Text>
                                        <Text style={styles.badge}>{a.badge}</Text>
                                    </View>
                                    <Text style={styles.itemDesc}>{a.description}</Text>
                                </View>
                            </View>
                        ))}
                    </AccordionSection>

                    {/* Houses */}
                    <AccordionSection
                        id="houses"
                        title={fr ? 'Les maisons' : 'Houses'}
                        isOpen={openSection === 'houses'}
                        onToggle={() => toggle('houses')}
                    >
                        {houses.map((h, i) => (
                            <View key={i} style={styles.item}>
                                <View style={styles.numberBubble}>
                                    <Text style={styles.numberText}>{h.number}</Text>
                                </View>
                                <View style={styles.itemBody}>
                                    <Text style={styles.itemName}>{h.name}</Text>
                                    <Text style={styles.itemDesc}>{h.description}</Text>
                                </View>
                            </View>
                        ))}
                    </AccordionSection>

                    {/* Glossary */}
                    <AccordionSection
                        id="glossary"
                        title={fr ? 'Glossaire' : 'Glossary'}
                        isOpen={openSection === 'glossary'}
                        onToggle={() => toggle('glossary')}
                    >
                        {glossary.map((g, i) => (
                            <View key={i} style={styles.item}>
                                <View style={styles.dotBubble}>
                                    <View style={styles.dot} />
                                </View>
                                <View style={styles.itemBody}>
                                    <Text style={styles.itemName}>{g.name}</Text>
                                    <Text style={styles.itemDesc}>{g.description}</Text>
                                </View>
                            </View>
                        ))}
                    </AccordionSection>

                    <View style={{ height: 48 }} />
                </ScrollView>
            </SafeAreaView>
        </View>
    );
}

// ─── Styles ───────────────────────────────────────────────────────────────────

const acc = StyleSheet.create({
    wrapper: {
        marginBottom: spacing.md,
        backgroundColor: colors.surfaceContainer,
        borderRadius: radius.xl,
        overflow: 'hidden',
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: spacing.xl,
        paddingVertical: spacing.lg,
    },
    headerText: {
        fontFamily: fonts.body.semiBold,
        fontSize: 15,
        color: colors.onSurface,
    },
    body: {
        paddingHorizontal: spacing.xl,
        paddingBottom: spacing.lg,
    },
});

const styles = StyleSheet.create({
    root: {
        flex: 1,
        backgroundColor: colors.surfaceLowest,
    },
    safe: { flex: 1 },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: spacing.xl,
        paddingVertical: spacing.lg,
    },
    backBtn: {
        width: 32,
        alignItems: 'flex-start',
    },
    headerTitle: {
        fontFamily: fonts.display.regular,
        fontSize: 18,
        color: colors.onSurface,
        letterSpacing: 0.2,
    },
    scrollContent: {
        paddingHorizontal: spacing.xl,
        paddingTop: spacing.md,
    },
    intro: {
        fontFamily: fonts.body.regular,
        fontSize: 14,
        color: colors.onSurfaceMuted,
        marginBottom: spacing.xl,
        lineHeight: 20,
    },

    // Items
    item: {
        flexDirection: 'row',
        gap: spacing.md,
        marginBottom: spacing.lg,
        alignItems: 'flex-start',
    },
    itemBody: { flex: 1 },
    itemRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: spacing.sm,
        marginBottom: spacing.xs,
    },
    itemName: {
        fontFamily: fonts.body.semiBold,
        fontSize: 14,
        color: colors.onSurface,
        marginBottom: spacing.xs,
    },
    itemDesc: {
        fontFamily: fonts.body.regular,
        fontSize: 13,
        lineHeight: 19,
        color: colors.onSurfaceMuted,
    },

    // Bubbles
    iconBubble: {
        width: 44,
        height: 44,
        borderRadius: radius.md,
        backgroundColor: colors.surfaceContainerHigh,
        alignItems: 'center',
        justifyContent: 'center',
        flexShrink: 0,
    },
    iconText: {
        fontSize: 20,
    },
    symbolBubble: {
        width: 44,
        height: 44,
        borderRadius: radius.md,
        alignItems: 'center',
        justifyContent: 'center',
        flexShrink: 0,
    },
    symbol: {
        fontSize: 18,
        lineHeight: 22,
    },
    symbolSmall: {
        fontSize: 10,
    },
    numberBubble: {
        width: 44,
        height: 44,
        borderRadius: radius.md,
        backgroundColor: `${colors.secondary}20`,
        alignItems: 'center',
        justifyContent: 'center',
        flexShrink: 0,
    },
    numberText: {
        fontFamily: fonts.body.bold,
        fontSize: 15,
        color: colors.secondary,
    },
    dotBubble: {
        width: 44,
        height: 44,
        alignItems: 'center',
        justifyContent: 'center',
        flexShrink: 0,
    },
    dot: {
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: colors.primary,
    },
    badge: {
        fontFamily: fonts.body.regular,
        fontSize: 11,
        color: colors.onSurfaceMuted,
        backgroundColor: colors.surfaceContainerHigh,
        paddingHorizontal: 6,
        paddingVertical: 2,
        borderRadius: radius.full,
    },
    pageTitle: {
        fontFamily: fonts.display.bold,
        fontSize: 32,
        color: colors.onSurface,
        marginBottom: spacing.md,
    },
});
